name: Silence
version: 0.6.1
main: net.madmanmarkau.Silence.Silence
author: MadManMarkAu
license: WTFPL
description: >
             Silence annoying players.
commands:
  silence_silence:
    description: Silences players.
    aliases: silence
    usage: /<command> <player> [ON|OFF|<seconds>]
    permission:
     - silence.query
     - silence.modify
  silence_silenceall:
    description: Silences all players.
    aliases: silenceall
    usage: /<command> [ON|OFF|<seconds>]
    permission:
     - silence.queryall
     - silence.modifyall
 