name: Silence
version: 0.5
main: net.madmanmarkau.Silence.Silence
author: MadManMarkAu
description: >
             Silence annoying players.
commands:
  silence_silence:
    description: Silences players.
    aliases: silence
    usage: /<command> <player> [ON|OFF|<seconds>]
