name: Silence
version: 0.9
main: net.madmanmarkau.Silence.Silence
author: MadManMarkAu, filbert66
license: WTFPL
description: >
             Silence/ignore annoying players.
commands:
  silence_silence:
    description: Silences players.
    aliases: silence
    usage: /<command> <player> [ON|OFF|<seconds>]
    permission:
     - silence.query
     - silence.modify
  silence_silenceall:
    description: Silences all players.
    aliases: silenceall
    usage: /<command> [ON|OFF|<seconds>]
    permission:
     - silence.queryall
     - silence.modifyall
  silence_ignore:
    description: Ignore specific player's chats, or query your ignore list.
    aliases: ignore
    usage: /<command> [<player> [ON|OFF|<seconds>]]
    permission:
      - silence.ignore

permissions:
    silence.*:
        description: Gives access to all permissions.
        default: false
        children:
            silence.query: true
            silence.modify: true
            silence.queryall: true
            silence.modifyall: true
            silence.ignore: true
